openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0

servers:
  - url: 'https'
paths:
  /accounts:
    post:
      summary: Create a new account
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: "New account"
              balance:
                amount: 50.00
                lastUpdate: '2023-12-07T12:00:00'
              transactions: []
              devise: "Ariary"
              type: "Banque"
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              example:
                id: 103
                name: "Nouveau Compte"
                balance:
                  amount: 50.00
                  lastUpdate: '2023-12-07T12:00:00'
                transactions: []
                devise: "Ariary"
                type: "Banque"



  /accounts/{accountId}:
    parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: integer
        description: ID of the account

    get:
      summary: Get account by ID
      tags:
        - Accounts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 101
                name: "Compte Courant"
                balance:
                  amount: 75.00
                  lastUpdate: '2023-12-07T12:00:00'
                transactions: []
                devise: "Ariary"
                type: "Banque"


    put:
      summary: Update account by ID
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            example:
              id: 108
              name: "Compte courant"
              balance:
                amount: 1975.00
                lastUpdate: '2023-11-07T14:00:00'
              transactions: []
              devise: "Ariary"
              type: "Mobile banking"
      responses:
        '200':
          description: Account updated successfully
          content:
            application/json:
              example:
                id: 109
                name: "Compte Courant"
                balance:
                  amount: 985.00
                  lastUpdate: '2023-12-07T12:00:00'
                transactions: []
                devise: "Ariary"
                type: "Cash"


  /transactions:
    get:
      summary: Get all transactions
      tags:
        - Transactions
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                transactions:
                  - id: 203
                    label: "Mobile banking"
                    amount: 3000.00
                    type: "credit"
                    date: '2023-01-15T10:30:00Z'
                  - id: 203
                    label: "bank loan"
                    amount: 30.00
                    date: '2023-01-20T08:15:00Z'
                    type: "debit"

    post:
      summary: Create a new transaction
      tags:
        - Transactions
      requestBody:
        required: true
        content:
          application/json:
            example:
              amount: 30.00
              date: '2023-01-20T08:15:00Z'
      responses:
        '201':
          description: Transaction created successfully
          content:
            application/json:
              example:
                id: 203
                label: "bank loan"
                amount: 30.00
                date: '2023-01-20T08:15:00Z'
                type: "debit"

  /transactions/{transactionId}:
    parameters:
      - name: transactionId
        in: path
        required: true
        schema:
          type: integer
        description: ID of the transaction

    get:
      summary: Get transaction by ID
      tags:
        - Transactions
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 201
                label: "cash deposit"
                amount: 20000.00
                date: '2022-01-21T09:00:00Z'
                type: "credit"

    put:
      summary: Update transaction by ID
      tags:
        - Transactions
      requestBody:
        required: true
        content:
          application/json:
            example:
              amount: 40.00
              date: '2023-01-22T09:00:00Z'
      responses:
        '200':
          description: Transaction updated successfully
          content:
            application/json:
              example:
                id: 201
                label: "bank loan"
                amount: 400000.00
                date: '2023-01-22T09:00:00Z'
                type: "credit"
  /currencies:
    get:
      summary: Get all currencies
      tags:
        - Currencies
      responses:
        '200':
          $ref: '#/components/responses/200Currency'

    post:
      summary: Create a new currency
      tags:
        - Currencies
      requestBody:
        required: true
        content:
          application/json:
            example:
              code: USD
              name: US Dollar
      responses:
        '201':
          $ref: '#/components/responses/200Currency'

  /currencies/{currencyId}:
    parameters:
      - name: currencyId
        in: path
        required: true
        schema:
          type: integer
        description: ID of the currency

    get:
      summary: Get currency by ID
      tags:
        - Currencies
      responses:
        '200':
          $ref: '#/components/responses/200Currency'

    put:
      summary: Update currency by ID
      tags:
        - Currencies
      requestBody:
        required: true
        content:
          application/json:
            example:
              code: EUR
              name: Euro
      responses:
        '200':
          $ref: '#/components/responses/200Currency'
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          example: "Saving Account"
        balance:
          type : object
          properties:
            amount:
              type: number
              example: 1200
            lastUpdate:
              type: string
              format: date-time
              example: "2023-12-07T12:00:00"
        transactions:
          type: array
          items: {}
        devise:
          type: string
          enum:
            - Bank
            - Mobile Banking
            - Cash
          example: "Ariary"
        type:
          type: string
          example: "Bank"
    Transaction:
      type: object
      properties:
        id:
          type: integer
        label :
          type: string
          example: "Bank loan"
        amount:
          type: number
        date:
          type: string
          format: date-time
        transactionType:
          type: string
          enum:
            - Debit
            - Credit
    Currency:
      type: object
      enum:
        - Euro
        - Ariary
      properties:
        id:
          type: integer
        code:
          type: string
          example: "EUR"
        name:
          type: string
          example : "Euro"
  responses:
    200Currency:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Currency'
    200Transaction:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Transaction'
    200Account:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Account'
